### ISSUE TITLE
Is this text to voice? 

### ISSUE THREAD

**Issue by jndq** [AdmTal/crowdcast#1]
I am listening to the podcast.
It's so hard to get used to this stuff!
So the script is written by AI – which AI?
Are these voices I hear real humans reading the scripts or is that computer generated as well?

**Comment by AdmTal** [comment]
Hey, yes - the script is written by AI, and the voice is generated by AI.

However, the input to the AI is user generated from the community on reddit.com/r/crowdcast.

Every week, there is a sticky thread, and the top 3 comments are used.  Here is the code that pulls them in: https://github.com/AdmTal/crowdcast/blob/main/main.py#L35-L36

Then, I use Open AI's GPT-4 to convert the comments into parts of a podcast script: https://github.com/AdmTal/crowdcast/blob/main/main.py#L39-L46

Later, I use https://elevenlabs.io/ to convert the script into voice: https://github.com/AdmTal/crowdcast/blob/main/main.py#L127-L157
