### ISSUE TITLE
Issue with the Intro prompt

### ISSUE THREAD

**Issue by rajtilakjee** [AdmTal/crowdcast#3]
I am facing issues while trying to generate the Intro using the prompt.

It keeps adding cues like `[INTRO MUSIC]`, `Host:`, and `[INTRO MUSIC FADES]` in the Intro, rest of the speech is working fine. I am using GPT-3.5-Turbo instead of GPT-4.

Have you faced a similar challenge? Can you guide me in some way? Thanks in advance. Raj.

**Comment by rajtilakjee** [comment]
I solved it! All I had to do was refactor the existing prompt using ChatGPT and voila, it solved all the issues. Sorry for disturbing you though.

**Comment by AdmTal** [comment]
Glad it worked out!
